# Generated by Django 4.2.3 on 2023-08-18 19:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZT',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ci_user', models.IntegerField()),
                ('cargo', models.CharField(default='No asignado', max_length=40)),
                ('email', models.CharField(default='No asignado', max_length=40, null=True)),
                ('telefono', models.CharField(default='No asignado', max_length=18, null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='access_users', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proj', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSol',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('78c6daf4-48d4-45e7-b2de-47b732b8b029'), editable=False, primary_key=True, serialize=False)),
                ('fecha_propuesto', models.DateField(auto_now_add=True, null=True)),
                ('fecha_comienzo', models.DateField(null=True)),
                ('fecha_culminado', models.DateField(null=True)),
                ('latest_mod', models.DateTimeField(auto_now=True)),
                ('id_esta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Estado_Info', to='appHCI.estadosol')),
            ],
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1f796c3a-bc44-42bc-883e-328a01292ed9'), editable=False, primary_key=True, serialize=False)),
                ('cod_solution', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True)),
                ('nombreSol', models.TextField(max_length=300)),
                ('coordinador_sol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Coordinador_Sol', to=settings.AUTH_USER_MODEL)),
                ('info_sol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='R_Info_Sol', to='appHCI.infosol')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSol', models.CharField(max_length=30)),
                ('descripcion_tipo_sol', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.IntegerField(default=uuid.UUID('14455142-4482-414d-a9b4-c0edde47b296'), editable=False, primary_key=True, serialize=False)),
                ('typeU', models.CharField(default='Invitado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='U_Negocios',
            fields=[
                ('id', models.IntegerField(default=uuid.UUID('cf8521c1-0284-43bf-a1ac-ccabfbe4f663'), editable=False, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=30, null=True)),
                ('piso', models.CharField(max_length=10, null=True)),
                ('email_negocios', models.CharField(max_length=40, null=True)),
                ('telef_negocios', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Trabaja',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0cd83645-8391-422a-aaf8-090417d8258e'), editable=False, primary_key=True, serialize=False)),
                ('descripcion_cargo', models.TextField(max_length=120)),
                ('cargo', models.CharField(max_length=30)),
                ('ingreso_cargo', models.DateField()),
                ('id_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_Solution_Trab', to='appHCI.solucion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_UserZT_Trab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suscritos',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c347d62e-e8a4-41c8-9331-8d7287697a22'), editable=False, primary_key=True, serialize=False)),
                ('fecha_sus', models.DateField(editable=False)),
                ('id_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_Solution_Suscrit', to='appHCI.solucion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_UserZT_Suscrit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solucion',
            name='negocios_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Negocios_Sol', to='appHCI.u_negocios'),
        ),
        migrations.AddField(
            model_name='infosol',
            name='id_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_TypeSol_Info', to='appHCI.typesol'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='tipo_U',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_TipoUser', to='appHCI.typeuser'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='access_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
