# Generated by Django 4.2.3 on 2023-07-26 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2bba2bb2-92b0-4a88-ae66-6e3d41c7ed0a'), editable=False, primary_key=True, serialize=False)),
                ('typeU', models.CharField(default='Invitado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserZT',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e894cbd5-06b4-4af6-b13b-8597f721a4c5'), editable=False, primary_key=True, serialize=False)),
                ('ci_user', models.IntegerField()),
                ('fecha_reg', models.DateField(null=True)),
                ('fecha_nac', models.DateField()),
                ('email', models.CharField(default='Email no asignado', max_length=40)),
                ('telefono', models.CharField(default='Telefono no asignado', max_length=18)),
                ('estado_user', models.BooleanField(default=True)),
                ('tipo_U', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='appHCI.typeuser')),
            ],
        ),
    ]
