# Generated by Django 4.2.3 on 2023-07-26 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3682d7fd-6a21-40e4-9b66-71d34aea6d37'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f72b4c4d-2cda-45ab-a699-07a268da3ad0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
