# Generated by Django 4.2.3 on 2023-08-18 19:10

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0002_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosol',
            name='descriptioSol',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a03b212a-1950-4de3-9eca-c48b4f768b20'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0374ff2-dc07-4e60-8779-a838b0fce718'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='nombreSol',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a5cc5ee-91f8-429b-afc8-8fda016d2309'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3e39739-8e03-4b7a-a2ba-1841398cbb61'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('fe8aaae9-c2d5-45b1-8770-fe61f23b5a89'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.IntegerField(default=uuid.UUID('95bd297c-dbe1-4e3d-97f4-e1c72ebcd269'), editable=False, primary_key=True, serialize=False),
        ),
    ]
