# Generated by Django 4.2.3 on 2023-07-26 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0002_alter_typeuser_id_alter_userzt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa69453e-d623-42f3-9971-a03f2d164ff7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aef2da4b-4526-4c1c-a39f-609758fe3cc1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
