# Generated by Django 4.2.3 on 2023-08-27 06:28

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0003_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.CharField(default=uuid.UUID('4d2a20ad-79dd-4eb5-91e4-b1def4a31feb'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.CharField(default=uuid.UUID('c794cbe9-5919-4f3d-9a70-1bdacfcd76ae'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.CharField(default=uuid.UUID('6f70e8f7-bd09-4f8f-8b77-deb9366b2793'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.CharField(default=uuid.UUID('f84c0cbf-0bd9-4693-ace5-85b4ff40ce76'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.CharField(default=uuid.UUID('33bfc3ee-a91f-4f4f-b392-b3598e72eff2'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
