# Generated by Django 4.2.3 on 2023-07-27 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0003_alter_typeuser_id_alter_userzt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proj', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSol',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('98e2365d-79bf-4955-875a-1c5c3c82a526'), editable=False, primary_key=True, serialize=False)),
                ('latest_mod', models.DateTimeField()),
                ('id_esta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Estado_Info', to='appHCI.estadosol')),
            ],
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f505da86-3444-4d48-b034-7cffac2aaabd'), editable=False, primary_key=True, serialize=False)),
                ('cod_solution', models.IntegerField(editable=False)),
                ('nombreSol', models.TextField(max_length=300)),
                ('fecha_propuesto', models.DateField()),
                ('fecha_comienzo', models.DateField()),
                ('fecha_culminado', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSol', models.CharField(max_length=30)),
                ('descripcion_tipo_sol', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='U_Negocios',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e6e7bc54-b9af-46cb-9639-b05bc6df1513'), editable=False, primary_key=True, serialize=False)),
                ('telef_negocios', models.CharField(max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62d6cfa6-9fd1-4a7a-b85a-e2007fd6a261'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6b6729a-b343-499a-b1fd-39ec7f61ddba'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='tipo_U',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_TipoUser', to='appHCI.typeuser'),
        ),
        migrations.CreateModel(
            name='Trabaja',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('43b97582-6950-4432-a7e2-1ddfa734d181'), editable=False, primary_key=True, serialize=False)),
                ('descripcion_cargo', models.TextField(max_length=120)),
                ('cargo', models.CharField(max_length=30)),
                ('ingreso_cargo', models.DateField()),
                ('id_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_Solution_Trab', to='appHCI.solucion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_UserZT_Trab', to='appHCI.userzt')),
            ],
        ),
        migrations.CreateModel(
            name='Suscritos',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('499e2d84-7e7e-4229-9e80-5b8a68673053'), editable=False, primary_key=True, serialize=False)),
                ('fecha_sus', models.DateField(editable=False)),
                ('id_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_Solution_Suscrit', to='appHCI.solucion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_UserZT_Suscrit', to='appHCI.userzt')),
            ],
        ),
        migrations.AddField(
            model_name='solucion',
            name='coordinador_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Coordinador_Sol', to='appHCI.userzt'),
        ),
        migrations.AddField(
            model_name='solucion',
            name='info_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Info_Sol', to='appHCI.infosol'),
        ),
        migrations.AddField(
            model_name='solucion',
            name='negocios_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='R_Negocios_Sol', to='appHCI.u_negocios'),
        ),
        migrations.AddField(
            model_name='infosol',
            name='id_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_TypeSol_Info', to='appHCI.typesol'),
        ),
    ]
