# Generated by Django 4.2.3 on 2023-07-27 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0004_estadosol_infosol_solucion_typesol_u_negocios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b67abe20-4f2e-4299-aa6b-acafb06a5401'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d8216b1-f948-4366-951b-d1542a34ffb7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa0e78d4-d3bd-4bb5-97aa-b888d293d36a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e96d497-3dd4-4cfc-a234-bb8d70238986'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6b23d1a-7b98-4a82-b71b-1cc58a24ecc8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0573ab0e-2f71-43d0-8f85-a266d67641eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26af777a-804c-4764-877f-082e8f33384d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
