# Generated by Django 4.2.3 on 2023-08-27 06:39

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0006_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.CharField(default=uuid.UUID('8ae291a9-ab7a-45db-9409-ed57b0d8522a'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.CharField(default=uuid.UUID('bb78cc93-e52d-4e12-af0d-4b932080b00c'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='info_sol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='R_Info_Sol', to='appHCI.infosol'),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.CharField(default=uuid.UUID('66e1a73d-bafb-4a3a-9e3c-bc92e48755b7'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.CharField(default=uuid.UUID('fa7774c5-94eb-4947-8ccc-d4737f9170f7'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.CharField(default=uuid.UUID('90d4ee78-3221-4a82-8752-18aad7e8278c'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
