# Generated by Django 4.2.3 on 2023-07-30 16:22

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appHCI', '0007_alter_infosol_id_alter_solucion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userzt',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userzt',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userzt',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='access_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='userzt',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='access_users', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userzt',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('424a8ee7-a057-4526-bc4b-6c91e411ea69'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e05f82-0690-416c-a267-82252d7d4fef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74f50697-59de-4404-a241-a4e1ea913ca3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae292432-32a9-40a8-96f0-b212e5704d81'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08090b4e-9a09-40ed-bc7d-e0d04906433e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5e2ed00-bbd7-4dbb-a1d9-68f60ba07b36'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5affee2-6586-4dcc-8af1-8932bad01b8c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='AccessUser',
        ),
    ]
