# Generated by Django 4.2.3 on 2023-08-18 20:21

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0009_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97d46cd7-61ae-4095-a105-b43d11fa26cf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b044bcca-fa9b-40f7-801f-01274676b853'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afd181c7-6ecc-4a5a-ba52-9305a6bf1c89'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb6f2e5b-9255-4bd0-a77f-3c292cb863f5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('da5f64b4-32c4-441a-b72a-88e1e4b9e4b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
