# Generated by Django 4.2.3 on 2023-08-27 06:43

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0009_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.CharField(default=uuid.UUID('2c18c3a8-a5ff-4241-a248-ed1d29d91922'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.CharField(default=uuid.UUID('428b5983-1fcf-4543-918f-55a21beecff5'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.CharField(default=uuid.UUID('47a3a113-f164-4770-9d43-2e1a9c30078b'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.CharField(default=uuid.UUID('ec22b18b-49ad-4997-9c9a-dcb65d8b47fe'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.CharField(default=uuid.UUID('a7d7ab35-ae31-42b5-81d9-483d2588e5a6'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
