# Generated by Django 4.2.3 on 2023-07-30 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0009_alter_infosol_id_alter_solucion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userzt',
            name='estado_user',
        ),
        migrations.RemoveField(
            model_name='userzt',
            name='fecha_reg',
        ),
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('87b735c5-ccd5-483e-a97e-5f4ea93062b1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6da508ce-96cd-4827-b392-1bf599f74d10'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa827a0f-521b-410a-8a5a-3295e4c6baff'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f371416-1142-4df1-959c-64c46e103d48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65d61fb0-19aa-48f2-befb-0fcaf24385cf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d28c1f0-b2cb-49a5-86db-ac3ee1dc7114'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af7853bf-70e2-4782-8edc-2b9a28844749'), editable=False, primary_key=True, serialize=False),
        ),
    ]
