# Generated by Django 4.2.3 on 2023-07-30 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0010_remove_userzt_estado_user_remove_userzt_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f06b89d-08d5-4ab0-987f-e4067d9efcf9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de32846e-29f5-417f-b01f-89f72fe2c0ca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5e28a6a-2267-4969-ba6d-69c65bd422bb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('287edda0-3767-4285-a572-6ca488e3f47c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec8ce9a6-f1ea-4085-9903-eb70c4e7489a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f59e5000-f4c8-4bfc-8238-e3fbd3d79928'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userzt',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e635369-4589-4708-a68f-9efbe5e8113b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
