# Generated by Django 4.2.3 on 2023-08-18 20:32

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0010_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e540e22-8030-4509-8534-466186ea54d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d69cf4b8-94da-4e51-af17-d60bc4508f4c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fcc9b63-4053-4e73-b029-f4142c957ab3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6d31b6e-1e91-4e2b-b231-f5f6919c8806'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typesol',
            name='descripcion_tipo_sol',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('d0a910e9-614c-4d4e-ac30-98d80d8fa3c0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
