# Generated by Django 4.2.3 on 2023-08-18 20:33

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0011_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d01b6f3-7092-4c34-bd50-9a41d178d164'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4402768-446e-4306-bd65-ded2ab18ca45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('556265cf-0b8f-43e8-a3e6-82b4d8c31203'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb4de58a-fbe7-428d-a707-bc0b3230924f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typesol',
            name='tipoSol',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('2c06f454-36cb-4c77-9b91-aaf99d01e263'), editable=False, primary_key=True, serialize=False),
        ),
    ]
