# Generated by Django 4.2.3 on 2023-08-15 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0012_alter_infosol_id_alter_solucion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('671e7a86-7c90-432e-b5c5-242896b04319'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08e8a5a1-1f8f-48f9-8de7-2e410ebff6a8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99b71211-86ec-43e3-89ae-b454feda0acb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68e4497c-4aa5-490d-80e2-dffa882a1e3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.BigIntegerField(default=uuid.UUID('b72b7fc7-fa49-478e-9937-9b93949f132f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='u_negocios',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9de5699-8794-4b5d-8f33-4207b193af8d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
