# Generated by Django 4.2.3 on 2023-08-18 20:58

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0012_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infosol',
            old_name='id_sol',
            new_name='id_type',
        ),
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('578279fa-52fe-4503-9caa-12c8e179c248'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86dce89d-be08-4ffa-849c-a36e5c26f47a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e6a0b09-65f8-4958-9850-fa92a13b52d8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7efb617-f1fa-42dd-a7d5-d1b2029f1ee8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('39628802-45e6-4cb6-a6b1-047095dcc569'), editable=False, primary_key=True, serialize=False),
        ),
    ]
