# Generated by Django 4.2.3 on 2023-08-27 06:46

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0012_alter_infosol_id_alter_solucion_cod_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.CharField(default=uuid.UUID('a260b287-d50d-444d-8ba5-e0d7cb4ad973'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.CharField(default=uuid.UUID('742a4f5a-033a-4e38-b689-53c25f6e8d9e'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.CharField(default=uuid.UUID('43f5af1e-54d7-47de-99bd-84a68c1fe624'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.CharField(default=uuid.UUID('9e979173-5c93-4adf-b32f-aa6bdc32a49b'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.CharField(default=uuid.UUID('546190ef-861b-42c8-bae7-774819765569'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
