# Generated by Django 4.2.3 on 2023-08-18 21:00

from django.db import migrations, models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHCI', '0013_rename_id_sol_infosol_id_type_alter_infosol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b41ede17-3d24-44ee-8f68-52cbbbceaf37'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='cod_solution',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('deda4f84-d9d5-45d6-96fe-c470ced36aec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9168d4a-3e43-4565-815a-2b79eb466d8c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabaja',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c825780-0efd-4ab9-8a99-39d6e446d835'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='id',
            field=models.IntegerField(default=uuid.UUID('e7ec09e2-15e3-4402-b595-dd7dec68a5bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
